---

- name: Install pip
  yum:
    name:
      - libselinux-python3
      - libsemanage-python3
      - policycoreutils-python3
      - python3-pip
    state: installed

- name: remove pip docker
  pip:
    name: docker
    state: absent

- name: pip packages
  pip:
    name:
      - setuptools
        #version: 42.0.2
      - docker-py
        #version: 1.10.6
      - requests
        #version: 2.22.0
    state: present
    
