---

- name: Install pip
  yum: name={{ item }} state=installed
  with_items:
    - libselinux-python
    - libsemanage-python
    - policycoreutils-python
    - python38-pip

- name: remove pip docker
  pip:
    name: docker
    state: absent

- name: pip packages
  pip: name={{ item.name }} state=latest
  with_items:
    - name: setuptools
      #version: 42.0.2
    - name: docker-py
      #version: 1.10.6
    - name: awscli
      #version: 1.16.308
    - name: requests
      #version: 2.22.0
    - name: openshift
      #version: 0.10.1
