---
- name: install network add-on
  command: kubectl apply -f https://docs.projectcalico.org/v3.17/manifests/canal.yaml
  # command: kubectl apply -f {{ kubernetes_host_dir }}/conf/kube-canal.yml

- name: join master replica node
  shell: |
   kubeadm reset -f
   KUBE_JOIN_CMD=$(cat /srv/services/kubernetes/conf/kubeadm_join_token | awk '/kubeadm join/,/--control/')
   bash -c "${KUBE_JOIN_CMD} --apiserver-advertise-address={{ net_internal_ip }}"
